version: '3.8'

services:
  db:
    ports:
      - "5433:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src

  frontend:
    ports:
      - "3000:3000"

  studio-frontend:
    ports:
      - "3001:3000"
    volumes:
      - ./studio-frontend:/app/src
